language: bash
services: docker
env:
  - WP_VERSION=5.5.4 ACF_PRO_VERSION=5.7.13
  - WP_VERSION=5.5.4 ACF_PRO_VERSION=5.8.14
  - WP_VERSION=5.5.4 ACF_PRO_VERSION=latest
  - WP_VERSION=5.6.3 ACF_PRO_VERSION=5.7.13
  - WP_VERSION=5.6.3 ACF_PRO_VERSION=5.8.14
  - WP_VERSION=5.6.3 ACF_PRO_VERSION=latest
  - WP_VERSION=latest ACF_PRO_VERSION=5.7.13
  - WP_VERSION=latest ACF_PRO_VERSION=5.8.14
  - WP_VERSION=latest ACF_PRO_VERSION=latest
script:
  - docker build --no-cache --rm --tag="wp-connector-wp-${WP_VERSION}-acf-${ACF_PRO_VERSION}" -f "Buildplan/Dockerfile" --build-arg ACFPRO_KEY="${ACF_PRO_KEY}" --build-arg WP_VERSION="${WP_VERSION}" --build-arg ACF_PRO_VERSION="${ACF_PRO_VERSION}" --build-arg GITHUB_OAUTH_TOKEN="${GITHUB_OAUTH}" .
  - docker run --rm -w "/plugin-dir" -v "$(pwd):/plugin-dir" -e MYSQL_HOST="localhost" -e CRE_PROJECT_ID="${PROJECT_ID}" -e CRE_USER_IDENTIFIER="${USER_IDENTIFIER}" -e CRE_TOKEN_SECRET="${TOKEN_SECRET}" "wp-connector-wp-${WP_VERSION}-acf-${ACF_PRO_VERSION}":latest
  - bash <(curl -s https://codecov.io/bash) -f "$(pwd)/tests/phpunit-coverage.xml"
notifications:
  email:
    recipients:
      - vsolovei@smartling.com
    on_success: change
    on_failure: always
