language: bash
services: docker
env:
  - PHP_version=5.6 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=4.9.8 ACF_PRO_VERSION=latest
  - PHP_version=5.6 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=4.9.9 ACF_PRO_VERSION=latest
  - PHP_version=5.6 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=4.9.10 ACF_PRO_VERSION=latest
  - PHP_version=5.6 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=5.0.4 ACF_PRO_VERSION=latest
  - PHP_version=5.6 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=5.1.1 ACF_PRO_VERSION=latest
  - PHP_version=5.6 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=5.2.2 ACF_PRO_VERSION=latest
  - PHP_version=5.6 WP_VERSION=latest ACF_PRO_VERSION=5.7.10
  - PHP_version=5.6 WP_VERSION=latest ACF_PRO_VERSION=5.7.12
  - PHP_version=5.6 WP_VERSION=latest ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=4.9.8 ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=4.9.9 ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=4.9.10 ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=5.0.4 ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=5.1.1 ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=5.2.2 ACF_PRO_VERSION=latest
  - PHP_version=7.0 WP_VERSION=latest ACF_PRO_VERSION=5.7.10
  - PHP_version=7.0 WP_VERSION=latest ACF_PRO_VERSION=5.7.12
  - PHP_version=7.0 WP_VERSION=latest ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=4.9.8 ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=4.9.9 ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=4.9.10 ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=5.0.4 ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=5.1.1 ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=5.2.2 ACF_PRO_VERSION=latest
  - PHP_version=7.1 WP_VERSION=latest ACF_PRO_VERSION=5.7.10
  - PHP_version=7.1 WP_VERSION=latest ACF_PRO_VERSION=5.7.12
  - PHP_version=7.1 WP_VERSION=latest ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=4.9.8 ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=4.9.9 ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=4.9.10 ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=5.0.4 ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=5.1.1 ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=5.2.2 ACF_PRO_VERSION=latest
  - PHP_version=7.2 WP_VERSION=latest ACF_PRO_VERSION=5.7.10
  - PHP_version=7.2 WP_VERSION=latest ACF_PRO_VERSION=5.7.12
  - PHP_version=7.2 WP_VERSION=latest ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=4.9.8 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=4.9.8 ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=4.9.9 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=4.9.9 ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=4.9.10 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=4.9.10 ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=5.0.4 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=5.0.4 ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=5.1.1 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=5.1.1 ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=5.2.2 ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=5.2.2 ACF_PRO_VERSION=latest
  - PHP_version=7.3 WP_VERSION=latest ACF_PRO_VERSION=5.7.10
  - PHP_version=7.3 WP_VERSION=latest ACF_PRO_VERSION=5.7.12
  - PHP_version=7.3 WP_VERSION=latest ACF_PRO_VERSION=latest
script:
  - docker build --no-cache --rm --tag="wp-connector-php-${PHP_version}-wp-${WP_VERSION}-acf-${ACF_PRO_VERSION}" -f "Buildplan/Dockerfile" --build-arg PHP_version="${PHP_version}" --build-arg ACFPRO_KEY="${ACF_PRO_KEY}" --build-arg WP_VERSION="${WP_VERSION}" --build-arg ACF_PRO_VERSION="${ACF_PRO_VERSION}" --build-arg GITHUB_OAUTH_TOKEN="${GITHUB_OAUTH}" .
  - docker run --rm -w "/plugin-dir" -v "$(pwd):/plugin-dir" -e MYSQL_HOST="localhost" -e CRE_PROJECT_ID="${PROJECT_ID}" -e CRE_USER_IDENTIFIER="${USER_IDENTIFIER}" -e CRE_TOKEN_SECRET="${TOKEN_SECRET}" "wp-connector-php-${PHP_version}-wp-${WP_VERSION}-acf-${ACF_PRO_VERSION}":latest
notifications:
  email:
    recipients:
      - pratushnyi@smartling.com
    on_success: change
    on_failure: always