parameters:
  user.identifier: ""
  user.secret: ""
  plugin.dir: "@=constant('SMARTLING_PLUGIN_DIR')"
  plugin.name: "wordpress-connector"
  plugin.upload: "@=constant('SMARTLING_PLUGIN_DIR')~constant('DIRECTORY_SEPARATOR')~'upload'"
  plugin.url: "@=service('wp.proxy').plugin_dir_url(constant('SMARTLING_PLUGIN_DIR')~constant('DIRECTORY_SEPARATOR')~'..')"
  plugin.version: "auto updated"
  plugin.domain: %plugin.name%
